language: go

go:
  - 1.16.x  

script:
  - ls /proc/sys/fs/binfmt_misc/
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - ls /proc/sys/fs/binfmt_misc/
  - uname -a
  - go version
  - make
